name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ofirfram/test
        ref: main
    
    - name: Extract data from file in another repository
      run: |
        cat testit.conf > extracted_data.txt
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: extracted_data
        path: extracted_data.txt
        
    - name: Checkout script repository
      uses: actions/checkout@v2
      with:
        repository: ofirfram/mygitactions
        ref: main
        
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: extracted_data
        path: data_file.txt
        
    - name: Run the script
      run: |
        python run.py data_file.txt
