name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ofirfram/test
        ref: main # or use the branch/tag/commit hash you want to checkout
    
    - name: Extract data from file in another repository
      run: |
        cat testit.conf > extracted_data.txt
        
    - name: Display contents
      run: |
        contents=$(<extracted_contents.txt)
        echo $contents
        
    - name: Display extracted data
      run: |
         python run.py

