name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Extract file contents
      run: |
        cat ofirfram/test/testit.conf > extracted_contents.txt
    - name: Display contents
      run: |
        contents=$(<extracted_contents.txt)
        echo $contents
        
    - name: Use contents in Python
      run: |
        python run.py
