name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ofirfram/test
        ref: main
    
    - name: Extract data from file in another repository
      run: |
        cat testit.conf >> extracted_data.txt
        
    - name: Read extracted data
      id: extract_data
      run: |
        contents=$(cat extracted_data.txt)
        echo "$contents"
        
    - name: Checkout script repository
      uses: actions/checkout@v2
      with:
        repository: ofirfram/mygitactions
        ref: main
        
    - name: Run the script
      run: |
        contents=$(cat extracted_data.txt)
        echo "$contents"
        python run.py data_file.txt
      env:
        contents: ${{ steps.extract_data.outputs.contents }}
