name: My Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout test repository
      uses: actions/checkout@v2
      with:
        repository: ofirfram/test
        ref: main
    
    - name: Extract data from test repository
      run: echo testit.conf 
        
    - name: Checkout mygitactions repository
      uses: actions/checkout@v2
      with:
        repository: ofirfram/mygitactions
        ref: main

    - name: Run the script with extracted data
      run: |
        python run.py
